#:import dp kivy.metrics.dp
<DatabaseScreen>:
    FloatLayout:
        BoxLayout:
            orientation: "vertical"
            padding: 15
            spacing: 10
            size_hint: 1, 1
            Label:
                id: title_label
                text: "Baza proizvoda i prodavnica"
                font_size: "15sp"
                size_hint_y: None
                height: dp(36)
            GridLayout:
                cols: 4
                spacing: dp(10)
                size_hint_y: None
                height: self.minimum_height
                row_default_height: dp(84)
                row_force_default: True
                IconTabButton:
                    id: tab_products
                    icon_source: app.assets_dir + "gorivo.png"
                    text: "Gorivo"
                    on_release: root.show_proizvodi()
                IconTabButton:
                    id: tab_stores
                    icon_source: app.assets_dir + "servisi.png"
                    text: "Servisi"
                    on_release: root.show_prodavnice()
                IconTabButton:
                    id: tab_categories
                    icon_source: app.assets_dir + "troskovi.png"
                    text: "Troskovi"
                    on_release: root.show_kategorije()
            GridLayout:
                id: extra_tabs_box
                cols: 4
                spacing: dp(10)
                size_hint_y: None
                height: self.minimum_height
                row_default_height: dp(84)
                row_force_default: True
            ScrollView:
                BoxLayout:
                    id: database_box
                    orientation: "vertical"
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: dp(4)
        BackButton:
            id: back_btn
            image_source: "assets/nazad_prazno.png"
            size_hint: None, None
            size: dp(110), dp(50)
            pos_hint: {"x": 0.02, "y": 0.02}
            on_release: root.go_back()
