#:import dp kivy.metrics.dp
<SettingsScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 15

        BoxLayout:
            size_hint_y: None
            height: dp(48)
            spacing: 10
            SecondaryButton:
                text: "< Nazad"
                size_hint_x: 0.3
                on_release: root.go_back()
            Label:
                text: "Podesavanja"
                font_size: "20sp"
                bold: True

        Label:
            text: "Boja teme aplikacije"
            font_size: "16sp"
            size_hint_y: None
            height: dp(30)
            color: 0.7, 0.7, 0.7, 1

        ScrollView:
            BoxLayout:
                id: theme_box
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                spacing: dp(10)
