#:import dp kivy.metrics.dp
<ShoppingListScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: 15
        spacing: 10

        BoxLayout:
            size_hint_y: None
            height: dp(48)
            spacing: 10

            Button:
                size_hint_x: None
                width: dp(110)
                background_normal: "assets/nazad_btn.png"
                background_down: "assets/nazad_btn.png"
                on_release: root.go_back()

            Label:
                id: store_label
                text: "Prodavnica: (izbor dolazi)"
                font_size: "16sp"

        BoxLayout:
            size_hint_y: None
            height: dp(30)
            Label:
                id: col_product
                text: "Proizvod"
                bold: True
            Label:
                id: col_qty
                text: "Kol."
                bold: True
                size_hint_x: 0.4
            Label:
                id: col_price
                text: "Cena/j."
                bold: True
                size_hint_x: 0.5
            Label:
                id: col_total
                text: "Total"
                bold: True
                size_hint_x: 0.5

        ScrollView:
            size_hint_y: 1
            BoxLayout:
                id: items_box
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height

        PrimaryButton:
            id: add_product_btn
            text: "+ Dodaj proizvod"
            size_hint_y: None
            height: dp(52)
            on_release: root.add_item()

        BoxLayout:
            size_hint_y: None
            height: dp(40)
            Label:
                id: total_word_label
                text: "UKUPNO:"
                bold: True
                font_size: "18sp"
            Label:
                id: total_label
                text: "0.00"
                bold: True
                font_size: "18sp"

        SecondaryButton:
            id: close_list_btn
            text: "Zatvori listu"
            size_hint_y: None
            height: dp(52)
            on_release: root.close_list()
