#:import dp kivy.metrics.dp
<ShoppingListScreen>:
    FloatLayout:
        BoxLayout:
            orientation: "vertical"
            padding: [15, 15, 15, dp(80)]
            spacing: 10
            size_hint: 1, 1
            pos_hint: {"x": 0, "y": 0}

            BoxLayout:
                size_hint_y: None
                height: dp(30)
                Label:
                    text: "Shopping List"
                    font_size: "18sp"
                    bold: True

            ScrollView:
                size_hint_y: 1
                BoxLayout:
                    id: items_box
                    orientation: "vertical"
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: dp(12)

            PrimaryButton:
                id: add_product_btn
                text: "+ Dodaj proizvod"
                size_hint_y: None
                height: dp(52)
                on_release: root.add_item()

            BoxLayout:
                size_hint_y: None
                height: dp(40)
                Label:
                    id: grand_total_word
                    text: "SVEUKUPNO:"
                    bold: True
                    font_size: "16sp"
                Label:
                    id: grand_total_label
                    text: "0.00"
                    bold: True
                    font_size: "16sp"

        Button:
            size_hint: None, None
            size: dp(110), dp(48)
            pos_hint: {"x": 0.03, "y": 0.03}
            background_normal: "assets/nazad_btn.png"
            background_down: "assets/nazad_btn.png"
            on_release: root.go_back()
